"""empty message

Revision ID: 602e6982692d
Revises: 2b7ce864fccc
Create Date: 2024-09-13 20:41:02.076936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602e6982692d'
down_revision = '2b7ce864fccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camping_rut', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('landscape', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.drop_column('rut_del_negocio')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('rut_del_negocio', sa.VARCHAR(length=12), nullable=False))
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('type')
        batch_op.drop_column('landscape')
        batch_op.drop_column('camping_rut')

    # ### end Alembic commands ###
