"""empty message

Revision ID: 752c3219a2b5
Revises: 95f364b4978a
Create Date: 2024-09-21 15:38:01.925248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '752c3219a2b5'
down_revision = '95f364b4978a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camping_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url_map_site', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url_photo_site', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('site_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'camping', ['camping_id'], ['id'])
        batch_op.drop_column('campsite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campsite_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('site_ibfk_1', 'camping', ['campsite_id'], ['id'])
        batch_op.drop_column('url_photo_site')
        batch_op.drop_column('url_map_site')
        batch_op.drop_column('review')
        batch_op.drop_column('camping_id')

    # ### end Alembic commands ###
